version: "3"
services:
  postgresql:
    image: postgres:16.3-alpine
    restart: always
    container_name: postgresql16.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=mgorder